### ISSUE TITLE
"HTTP Error 404: Not Found" error while training bart model

### ISSUE THREAD

**Issue by dinethnarada** [tanyuqian/progressive-generation#3]
**Environment**
In google colab

- torch=1.2.0
- transformers=2.5.1
- fairseq=0.9.0

**Task**
I tried to train bart model for wp dataset.
`!python train.py --dataset wp --prog_steps null-full --first_model bart`

**Error Message**

`Downloading: "https://github.com/pytorch/fairseq/archive/master.zip" to /root/.cache/torch/hub/master.zip
Traceback (most recent call last):
  File "bart_finetune.py", line 73, in <module>
    fire.Fire(main)
  File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "bart_finetune.py", line 46, in main
    bart = BART()
  File "/content/drive/My Drive/BART/progressive-generation/models/bart.py", line 24, in __init__
    self._model = BARTModelWrapper()
  File "/content/drive/My Drive/BART/progressive-generation/models/bart_utils.py", line 16, in __init__
    self._interface = torch.hub.load('pytorch/fairseq', 'bart.large')
  File "/usr/local/lib/python3.7/dist-packages/torch/hub.py", line 337, in load
    repo_or_dir = _get_cache_or_reload(repo_or_dir, force_reload, verbose)
  File "/usr/local/lib/python3.7/dist-packages/torch/hub.py", line 144, in _get_cache_or_reload
    download_url_to_file(url, cached_file, progress=False)
  File "/usr/local/lib/python3.7/dist-packages/torch/hub.py", line 394, in download_url_to_file
    u = urlopen(req)
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found`

**Additional Tasks**
I tried uninstalling torch=1.2.0 version and install torch=1.9.1(new). Then it came with this error message

`Traceback (most recent call last):
  File "bart_finetune.py", line 73, in <module>
    fire.Fire(main)
  File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "bart_finetune.py", line 46, in main
    bart = BART()
  File "/content/drive/My Drive/BART/progressive-generation/models/bart.py", line 24, in __init__
    self._model = BARTModelWrapper()
  File "/content/drive/My Drive/BART/progressive-generation/models/bart_utils.py", line 16, in __init__
    self._interface = torch.hub.load('pytorch/fairseq', 'bart.large')
  File "/usr/local/lib/python3.7/dist-packages/torch/hub.py", line 362, in load
    repo_or_dir = _get_cache_or_reload(repo_or_dir, force_reload, verbose)
  File "/usr/local/lib/python3.7/dist-packages/torch/hub.py", line 162, in _get_cache_or_reload
    _validate_not_a_forked_repo(repo_owner, repo_name, branch)
  File "/usr/local/lib/python3.7/dist-packages/torch/hub.py", line 124, in _validate_not_a_forked_repo
    with urlopen(url) as r:
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: rate limit exceeded`

Also I tried with bart.base model + adding force_reload=True params to the 
`torch.hub.load()`
line. Same error messages occurs.

How can I overcome with the issue?

**Comment by dinethnarada** [comment]
using torch.hub.load('pythorch/fairseq:main","xxx") this issue can be solved!
